name: CD

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log deployment
      run: echo "Deployed!"
