name: CI - Pull Requests

on:
  pull_request:
    branches: '*'
  workflow_run:
    workflows: ["CI - Push Events"]
    types:
      - completed

permissions:
      contents: write
      checks: write
      pull-requests: write

jobs:
  generate_reports:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: test-results

    - name: Download Base Test Results
      uses: actions/download-artifact@v2
      with:
        name: base-test-results
        path: base-test-results

    - name: Download CTRF Results
      uses: actions/download-artifact@v2
      with:
        name: ctrf-results
        path: test-results

    - name: Jest Coverage Report Action
      id: coverage
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-file: test-results/test-results.json
        base-coverage-file: base-test-results/test-results.json
        output: comment, report-markdown
        annotations: coverage

    - name: Comment Coverage Report
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
        
    - name: Publish CTRF Test Summary Results
      run: npx github-actions-ctrf summary test-results/ctrf-results.json
      if: always()

    - name: Publish CTRF Detailed Test Summary Results
      run: npx github-actions-ctrf tests test-results/ctrf-results.json
      if: always()

    - name: Publish CTRF Failed Test Summary Results
      run: npx github-actions-ctrf failed test-results/ctrf-results.json
      if: always()

  code_analysis:
    runs-on: ubuntu-latest
    needs: generate_reports

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.3.2/dependency-check-6.3.2-release.zip
        unzip dependency-check-6.3.2-release.zip
    
    - name: Install dependencies
      run: npm ci
        
    - name: Run Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh --project MyProject --out ./dependency-check-report --scan . --format ALL --disableAssembly --disableNodeAudit
        
    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: dependency-check-report

  security_analysis:
    runs-on: ubuntu-latest
    needs: generate_reports

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/security"
