name: CI - Push Events

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm ci

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Build Docker image
      run: docker build -t pd-test-task-devops .

    - name: Lint code
      run: docker run --rm pd-test-task-devops npm run lint > lint-results.txt

    - name: Run tests in Docker container
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        docker run --rm -e API_TOKEN=$API_TOKEN -v $PWD/test-results:/usr/src/app/test-results pd-test-task-devops bash -c "npm test -- --json --outputFile=/usr/src/app/test-results/test-results.json && chmod -R 755 /usr/src/app/test-results && node jest-to-ctrf.js"

    - name: Fetch base branch for comparison
      run: git fetch origin ${{ github.ref }} --depth=1000

    - name: Stash changes
      run: git diff --quiet || git stash

    - name: Checkout base branch
      run: git checkout ${{ github.ref }}

    - name: Install dependencies on base branch
      run: npm ci

    - name: Run tests and generate coverage report on base branch
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        npm test -- --json --outputFile=.base_test_results/test-results.json --coverage --coverageDirectory=.base_test_results && chmod -R 755 .base_test_results

    - name: Checkout push branch
      run: git checkout ${{ github.head_ref }}

    - name: Apply stashed changes
      run: |
        if git stash list | grep -q 'stash@{0}'; then
          git stash pop
        else
          echo "No changes to apply from stash"
        fi

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/test-results.json

    - name: Upload Base Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: base-test-results
        path: .base_test_results/test-results.json

    - name: Upload CTRF Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ctrf-results
        path: test-results/ctrf-results.json
