name: Code Analysis

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Check for Dependency Updates
        uses: dependabot/fetch-metadata@v1

  dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.3.2/dependency-check-6.3.2-release.zip
          unzip dependency-check-6.3.2-release.zip

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project MyProject --out ./dependency-check-report --scan . --format ALL

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report
